<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';

  interface Props {
    onComplete?: () => void;
    asModal?: boolean;
  }

  let { onComplete, asModal = false }: Props = $props();

  let step = $state(1);
  let name = $state('');
  let email = $state('');
  let pilotLicense = $state('');
  let licenseType = $state('');
  let licenseCountry = $state('');
  let loading = $state(false);
  let error = $state('');

  async function completeSetup() {
    if (!name.trim()) {
      error = 'Please enter your name';
      return;
    }

    loading = true;
    error = '';

    try {
      const user = {
        id: '', // Will be generated by backend
        name: name.trim(),
        email: email.trim() || null,
        pilot_license_number: pilotLicense.trim() || null,
        license_type: licenseType.trim() || null,
        license_country: licenseCountry.trim() || null,
        created_at: '',
        updated_at: ''
      };

      const userId = await invoke('create_user', { user });

      // Call callback if provided, otherwise reload
      if (onComplete) {
        onComplete();
      } else {
        window.location.reload();
      }
    } catch (e) {
      error = `Failed to create profile: ${e}`;
      loading = false;
    }
  }

  function handleBackdropClick(e: MouseEvent) {
    // Only close if clicking the backdrop itself, not the modal content
    if (e.target === e.currentTarget && onComplete) {
      onComplete();
    }
  }
</script>

<!-- Conditional modal backdrop wrapper -->
<svelte:element this={asModal ? 'div' : 'div'} class={asModal ? 'fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4' : ''} onclick={asModal ? handleBackdropClick : undefined} role={asModal ? 'button' : undefined} tabindex={asModal ? 0 : undefined}>
  <div class={asModal ? 'bg-white dark:bg-gray-800 rounded-lg shadow-2xl p-8 max-w-2xl w-full max-h-[90vh] overflow-y-auto' : 'max-w-2xl mx-auto'} onclick={(e) => asModal && e.stopPropagation()}>
    <div class={asModal ? '' : 'bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8'}>
    <!-- Progress Steps -->
    <div class="mb-8">
      <div class="flex items-center justify-center space-x-4">
        <div class="flex items-center">
          <div class={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
            step >= 1 ? 'bg-primary-600 text-white' : 'bg-gray-300 text-gray-600'
          }`}>
            1
          </div>
          <span class="ml-2 text-sm font-medium text-gray-700 dark:text-gray-300">Profile</span>
        </div>
        <div class="w-16 h-1 bg-gray-300 dark:bg-gray-600"></div>
        <div class="flex items-center">
          <div class={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
            step >= 2 ? 'bg-primary-600 text-white' : 'bg-gray-300 text-gray-600'
          }`}>
            2
          </div>
          <span class="ml-2 text-sm font-medium text-gray-700 dark:text-gray-300">Pilot Info</span>
        </div>
      </div>
    </div>

    {#if error}
      <div class="mb-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded">
        {error}
      </div>
    {/if}

    {#if step === 1}
      <!-- Step 1: Basic Profile -->
      <div>
        <h2 class="text-2xl font-bold mb-2 text-gray-900 dark:text-white">
          Welcome to Flight Tracker Pro
        </h2>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          Let's set up your profile to get started
        </p>

        <div class="space-y-4">
          <div>
            <label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Full Name *
            </label>
            <input
              id="name"
              type="text"
              bind:value={name}
              class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              placeholder="John Doe"
              required
            />
          </div>

          <div>
            <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Email (Optional)
            </label>
            <input
              id="email"
              type="email"
              bind:value={email}
              class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              placeholder="john@example.com"
            />
          </div>
        </div>

        <div class="mt-8 flex justify-between">
          <div></div>
          <button
            onclick={() => step = 2}
            disabled={!name.trim()}
            class="px-6 py-2 bg-primary-600 hover:bg-primary-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white rounded-lg font-medium transition"
          >
            Next
          </button>
        </div>
      </div>
    {:else if step === 2}
      <!-- Step 2: Pilot Information (Optional) -->
      <div>
        <h2 class="text-2xl font-bold mb-2 text-gray-900 dark:text-white">
          Pilot Information
        </h2>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          Optional: Add your pilot license details for logbook features
        </p>

        <div class="space-y-4">
          <div>
            <label for="license" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Pilot License Number
            </label>
            <input
              id="license"
              type="text"
              bind:value={pilotLicense}
              class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              placeholder="e.g., 123456789"
            />
          </div>

          <div>
            <label for="licenseType" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              License Type
            </label>
            <select
              id="licenseType"
              bind:value={licenseType}
              class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            >
              <option value="">Select type...</option>
              <option value="PPL">Private Pilot License (PPL)</option>
              <option value="CPL">Commercial Pilot License (CPL)</option>
              <option value="ATPL">Airline Transport Pilot License (ATPL)</option>
              <option value="SPL">Student Pilot License (SPL)</option>
            </select>
          </div>

          <div>
            <label for="country" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Issuing Country
            </label>
            <input
              id="country"
              type="text"
              bind:value={licenseCountry}
              class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              placeholder="e.g., USA, UK, Canada"
            />
          </div>
        </div>

        <div class="mt-8 flex justify-between">
          <button
            onclick={() => step = 1}
            class="px-6 py-2 bg-gray-300 hover:bg-gray-400 text-gray-700 rounded-lg font-medium transition"
          >
            Back
          </button>
          <button
            onclick={completeSetup}
            disabled={loading}
            class="px-6 py-2 bg-green-600 hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white rounded-lg font-medium transition"
          >
            {loading ? 'Creating...' : 'Complete Setup'}
          </button>
        </div>
      </div>
    {/if}
    </div>
  </div>
</svelte:element>
